name: sms_receiver
description: Android SMS Receiver API without permission required.
version: 0.4.0
homepage: https://github.com/iqbalmineraltown/flutter_sms_receiver

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.oval.sms_receiver
        pluginClass: SmsReceiverPlugin
      ios:
        pluginClass: SmsReceiverPlugin

  uses-material-design: true
